artifact_uri: file:///home/user1/MLops/mlops_all/docker/stores/model/0/59d3ec31808f4ea7a8173a221a50856a/artifacts
end_time: 1646736259187
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 59d3ec31808f4ea7a8173a221a50856a
run_uuid: 59d3ec31808f4ea7a8173a221a50856a
source_name: ''
source_type: 4
source_version: ''
start_time: 1646736259174
status: 3
tags: []
user_id: user1
