artifact_uri: file:///home/user1/MLops/mlops_all/docker/stores/model/0/636217c72e6447d79d5ba0834bffd830/artifacts
end_time: 1646736282652
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 636217c72e6447d79d5ba0834bffd830
run_uuid: 636217c72e6447d79d5ba0834bffd830
source_name: ''
source_type: 4
source_version: ''
start_time: 1646736282640
status: 3
tags: []
user_id: user1
