artifact_uri: file:///home/user1/MLops/mlops_all/docker/stores/model/0/f197af56942d4427afbed9f7e3e0df40/artifacts
end_time: 1646736317579
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f197af56942d4427afbed9f7e3e0df40
run_uuid: f197af56942d4427afbed9f7e3e0df40
source_name: ''
source_type: 4
source_version: ''
start_time: 1646736317566
status: 3
tags: []
user_id: user1
