artifact_uri: file:///home/user1/MLops/mlops_all/docker/stores/model/0/350c38e14a7b40308a47c0bb5ae053c8/artifacts
end_time: 1646736237669
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 350c38e14a7b40308a47c0bb5ae053c8
run_uuid: 350c38e14a7b40308a47c0bb5ae053c8
source_name: ''
source_type: 4
source_version: ''
start_time: 1646736237657
status: 3
tags: []
user_id: user1
