artifact_uri: file:///home/user1/MLops/mlops_all/docker/stores/model/0/b0dd45b9d27e4673b42b8adb091ad6a3/artifacts
end_time: 1646736113132
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b0dd45b9d27e4673b42b8adb091ad6a3
run_uuid: b0dd45b9d27e4673b42b8adb091ad6a3
source_name: ''
source_type: 4
source_version: ''
start_time: 1646736113118
status: 3
tags: []
user_id: user1
