artifact_uri: file:///home/user1/MLops/mlops_all/mlops_test/stores/model/0/9a8a4e5952ad4193b1fd71bcb7bcd50a/artifacts
end_time: 1646706921723
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9a8a4e5952ad4193b1fd71bcb7bcd50a
run_uuid: 9a8a4e5952ad4193b1fd71bcb7bcd50a
source_name: ''
source_type: 4
source_version: ''
start_time: 1646706897577
status: 3
tags: []
user_id: user1
