artifact_uri: file:///home/user1/MLops/mlops_all/docker/stores/model/0/f5412349a2d2467f987ecc1bfed29638/artifacts
end_time: 1646736350781
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f5412349a2d2467f987ecc1bfed29638
run_uuid: f5412349a2d2467f987ecc1bfed29638
source_name: ''
source_type: 4
source_version: ''
start_time: 1646736350768
status: 3
tags: []
user_id: user1
